### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FastxRecord'

### ISSUE THREAD

**Issue by endrebak** [CollasLab/edd#11]
```bash
~/anaconda3/envs/py27/bin/edd --bin-size 1000 --fdr 0.05 -g 5 -p 5 hg18.chromsizes unalignable test.bam control.bam results
Traceback (most recent call last):
  File "/local/home/endrebak/anaconda3/envs/py27/bin/edd", line 133, in <module>
    import eddlib.experiment
  File "/local/home/endrebak/anaconda3/envs/py27/lib/python2.7/site-packages/eddlib/experiment.py", line 17, in <module>
    import read_bam
  File "libcfaidx.pxd", line 51, in init eddlib.read_bam
AttributeError: 'module' object has no attribute 'FastxRecord'
```

**Comment by blankful** [comment]
so, do you solve this problem?

**Comment by endrebak** [comment]
Nope :/
