### ISSUE TITLE
Error in reading bam file

### ISSUE THREAD

**Issue by salmonm** [CollasLab/edd#12]
Hello
I'm trying to run EDD for the first time and I got the following error which I assume is related to reading the bam file
Traceback (most recent call last):
  File "/opt/miniconda2/bin/edd", line 133, in <module>
    import eddlib.experiment
  File "/opt/miniconda2/lib/python2.7/site-packages/eddlib/experiment.py", line 17, in <module>
    import read_bam
  File "libcfaidx.pxd", line 51, in init eddlib.read_bam (eddlib/read_bam.c:8007)
AttributeError: 'module' object has no attribute 'PersistentFastqProxy'

Any idea what is wrong?
Thanks
Mali

**Comment by FatihSarigol** [comment]
What's wrong is that a package/program version dependency problem prevents `pysam` from working which is required by EDD to read bam files by wrapping another program `htslib`. Not sure which installation method and which versions were used for this post 3 years ago, but the most recent bioconda build `1.1.19` also give the similar error.

I tried to install the `1.1.18` version too but that build was incomplete, missing some package dependencies.

I checked out the versions of the programs and noticed that in the current EDD conda build `pysam` is version `0.10.0` but that version was designed to wrap `htslib` version `1.3.2` while in the EDD conda build the htslib version is `1.9` and this causes pysam to not work apparently.
https://pysam.readthedocs.io/en/latest/release.html#release-0-10-0

I first updated both to the most recent versions but that did not work, likely because this time some other old version packages caused dependency issue with the upgraded two.

I tried downgrading htslib to `1.3.2` and that worked.

For anyone that wants to use EDD today, the easiest way to install it is then via conda, first:

`conda create -n EDD -c bioconda edd
`

then after installation is completed, downgrade htslib:

`conda install htslib=1.3.2
`

Info about how to install bioconda:
https://bioconda.github.io/user/install.html
