### ISSUE TITLE
AttributeError: 'module' object has no attribute '__version__'

### ISSUE THREAD

**Issue by Mingsenli** [CollasLab/edd#17]
Hello, edd is an useful tool, and i really need it. Thank you for your contribution and sharing.

When i run edd, the following error was made. How can i solve this problem? As a beginner,  i hope to get a detailed solution.
 Looking forward to  your reply. Thank you.

edd --write-log-ratios --write-bin-scores \
chrNameLength.txt hg19.blacklist.merge.bed \
H3K9me2_ab.rmdup.bam input.rmdup.bam H3K9me2_ab

Traceback (most recent call last):
  File "/data/User/limingsen/.conda/envs/EDD/bin/edd", line 133, in <module>
    import eddlib.experiment
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/eddlib/experiment.py", line 18, in <module>
    import logit
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/eddlib/logit.py", line 3, in <module>
    from statsmodels.stats.proportion import proportion_confint
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/statsmodels/stats/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/data/User/limingsen/.conda/envs/EDD/lib/python2.7/site-packages/statsmodels/compat/numpy.py", line 46, in <module>
    NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'

**Comment by zhangshuli-stu** [comment]
hello, do you solve the problem? I also have the same problem and do not know how to solve. If it is convenient, could you please help me? I will be very grateful.

**Comment by Mingsenli** [comment]
I am so sorry. I also do not solve this problem.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Jan 8, 2022 11:15 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [CollasLab/edd] AttributeError: 'module' object has no attribute '__version__' (#17)

&nbsp;



 
hello, do you solve the problem? I also have the same problem and do not know how to solve. If it is convenient, could you please help me? I will be very grateful.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangshuli-stu** [comment]
Thank you very much!
Best wishes!
















At 2022-01-22 17:42:05, "Mingsenli" ***@***.***> wrote:

I am so sorry. I also do not solve this problem.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Jan 8, 2022 11:15 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;; ***@***.***&gt;;
Subject: &nbsp;Re: [CollasLab/edd] AttributeError: 'module' object has no attribute '__version__' (#17)

&nbsp;




hello, do you solve the problem? I also have the same problem and do not know how to solve. If it is convenient, could you please help me? I will be very grateful.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmalzl** [comment]
As far as my investigation went I found that it is actually not EDD that is causing the problem but rather `statsmodels` which apparently is incompatible with python 2.7 from it 0.11 version (also see [here](https://github.com/statsmodels/statsmodels/issues/7948)). Thus, I would say a quick solution might be getting an older version of statsmodels (like 0.10)

**Comment by zhangshuli-stu** [comment]
Thank you very much, I have found  the statsmodels==0.6.1 can work well.
















At 2022-02-13 17:03:06, "Daniel Malzl" ***@***.***> wrote:

As far as my investigation went I found that it is actually not EDD that is causing the problem but rather statsmodels which apparently is incompatible with python 2.7 from it 0.11 version (also see here). Thus, I would say a quick solution might be getting an older version of statsmodels (like 0.10)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mingsenli** [comment]
Thank you for helping to solve this problem.&nbsp;
Your help has brought me great convenience.
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Feb 14, 2022 09:31 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [CollasLab/edd] AttributeError: 'module' object has no attribute '__version__' (#17)

&nbsp;



 Thank you very much, I have found  the statsmodels==0.6.1 can work well.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 At 2022-02-13 17:03:06, "Daniel Malzl" ***@***.***&gt; wrote:
 
 As far as my investigation went I found that it is actually not EDD that is causing the problem but rather statsmodels which apparently is incompatible with python 2.7 from it 0.11 version (also see here). Thus, I would say a quick solution might be getting an older version of statsmodels (like 0.10)
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangshuli-stu** [comment]
No thanks, I am very glad to help you.


Best regard,
Shuli
















At 2022-03-07 11:31:40, "Mingsenli" ***@***.***> wrote:

Thank you for helping to solve this problem.&nbsp;
Your help has brought me great convenience.
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Feb 14, 2022 09:31 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;; ***@***.***&gt;;
Subject: &nbsp;Re: [CollasLab/edd] AttributeError: 'module' object has no attribute '__version__' (#17)

&nbsp;



Thank you very much, I have found the statsmodels==0.6.1 can work well.
















At 2022-02-13 17:03:06, "Daniel Malzl" ***@***.***&gt; wrote:

As far as my investigation went I found that it is actually not EDD that is causing the problem but rather statsmodels which apparently is incompatible with python 2.7 from it 0.11 version (also see here). Thus, I would say a quick solution might be getting an older version of statsmodels (like 0.10)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***&gt;
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
