### ISSUE TITLE
Unable to install EDD

### ISSUE THREAD

**Issue by ghost** [CollasLab/edd#2]
Dear Developers,
I'm having an error when trying to install EDD through pip, could you please help me to solve it?
Seems that is trying to look for pysam (0.8.0) and finds version 0.7.5, but when I do `$ pip freeze`

```
[...]
pysam==0.8.3
[...]
```

Below I paste the install log. Also I noticed some issues with **eddlib/read_bam.c**

``` bash
$ pip install edd
```

```
Downloading/unpacking edd
  Downloading edd-1.1.13.tar.gz
  Running setup.py egg_info for package edd

###########
WARNING
###########
EDD requires pysam version 0.8.0 or greater, but the detected version was 0.7.5.The installation might not work.


Requirement already satisfied (use --upgrade to upgrade): Logbook in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): pybedtools in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): statsmodels in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): patsy in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): pandas in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): scipy in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): numpy in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from edd)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from pandas->edd)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages (from python-dateutil->edd)

Installing collected packages: edd
Running setup.py install for edd

###########
WARNING
###########
EDD requires pysam version 0.8.0 or greater, but the detected version was 0.7.5.The installation might not work.

cythoning eddlib/read_bam.pyx to eddlib/read_bam.c
building 'eddlib.read_bam' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/RSeQC-2.6.1-py2.7-linux-x86_64.egg/pysam -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/RSeQC-2.6.1-py2.7-linux-x86_64.egg/pysam/include/samtools -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/RSeQC-2.6.1-py2.7-linux-x86_64.egg/pysam/include/tabix -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include -I/software/mb/el6.3/python/pythons/CPython-2.7.9/include/python2.7 -c eddlib/read_bam.c -o build/temp.linux-x86_64-2.7/eddlib/read_bam.o
En el fichero incluído de /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804,
de /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
de /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
de eddlib/read_bam.c:250:
/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: aviso: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"


eddlib/read_bam.c:256:25: error: htslib_util.h: File or dir not exist
eddlib/read_bam.c:261:26: error: pysam_stream.h: File or dir not exist
eddlib/read_bam.c:265:26: error: samfile_util.h: File or dir not exist
eddlib/read_bam.c:855: error: expected specifier-qualifier-list before ‘kseq_t’
eddlib/read_bam.c:871: error: expected specifier-qualifier-list before ‘kseq_t’
eddlib/read_bam.c:1209: error: expected specifier-qualifier-list before ‘kseq_t’
error: command 'gcc' failed with exit status 1


Complete output from command /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/bin/python -c "import setuptools;__file__='/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/build/edd/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9R4UxR-record/install-record.txt --single-version-externally-managed --install-headers /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/include/site/python2.7:

###########
WARNING
###########
EDD requires pysam version 0.8.0 or greater, but the detected version was 0.7.5.The installation might not work.
running install

running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/eddlib
copying eddlib/estimate.py -> build/lib.linux-x86_64-2.7/eddlib
copying eddlib/logit.py -> build/lib.linux-x86_64-2.7/eddlib
copying eddlib/load_params.py -> build/lib.linux-x86_64-2.7/eddlib
copying eddlib/experiment.py -> build/lib.linux-x86_64-2.7/eddlib
copying eddlib/__init__.py -> build/lib.linux-x86_64-2.7/eddlib
copying eddlib/util.py -> build/lib.linux-x86_64-2.7/eddlib
creating build/lib.linux-x86_64-2.7/eddlib/algorithm
copying eddlib/algorithm/unalignable_regions.py -> build/lib.linux-x86_64-2.7/eddlib/algorithm
copying eddlib/algorithm/monte_carlo.py -> build/lib.linux-x86_64-2.7/eddlib/algorithm
copying eddlib/algorithm/max_segments.py -> build/lib.linux-x86_64-2.7/eddlib/algorithm
copying eddlib/algorithm/__init__.py -> build/lib.linux-x86_64-2.7/eddlib/algorithm
copying eddlib/default_parameters.conf -> build/lib.linux-x86_64-2.7/eddlib
running build_ext
cythoning eddlib/read_bam.pyx to eddlib/read_bam.c
building 'eddlib.read_bam' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/eddlib

gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/RSeQC-2.6.1-py2.7-linux-x86_64.egg/pysam -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/RSeQC-2.6.1-py2.7-linux-x86_64.egg/pysam/include/samtools -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/RSeQC-2.6.1-py2.7-linux-x86_64.egg/pysam/include/tabix -I/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include -I/software/mb/el6.3/python/pythons/CPython-2.7.9/include/python2.7 -c eddlib/read_bam.c -o build/temp.linux-x86_64-2.7/eddlib/read_bam.o

In the included file of /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804,
de /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
de /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
de eddlib/read_bam.c:250:

/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: aviso: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"


eddlib/read_bam.c:256:25: error: htslib_util.h: File or dir not exist
eddlib/read_bam.c:261:26: error: pysam_stream.h: File or dir not exist
eddlib/read_bam.c:265:26: error: samfile_util.h: File or dir not exist
eddlib/read_bam.c:855: error: expected specifier-qualifier-list before ‘kseq_t’
eddlib/read_bam.c:871: error: expected specifier-qualifier-list before ‘kseq_t’
eddlib/read_bam.c:1209: error: expected specifier-qualifier-list before ‘kseq_t’
error: command 'gcc' failed with exit status 1


Cleaning up...
Command /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/bin/python -c "import setuptools;__file__='/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/build/edd/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9R4UxR-record/install-record.txt --single-version-externally-managed --install-headers /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/include/site/python2.7 failed with error code 1 in /nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/build/edd

Traceback (most recent call last):
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 23: ordinal not in range(128)
```

I'm trying to install it in a server with SL6.5:

```
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: Scientific
Description:    Scientific Linux release 6.5 (Carbon)
Release:    6.5
Codename:   Carbon
```

Thanks for your help,

**Comment by ghost** [comment]
I was able to install it under Ubuntu 14.04LTS, but would be great if you could help to install on SL65. Thanks for your help

**Comment by eivindgl** [comment]
Hi,

The detected version of pysam when you tried to install EDD was 0.7.5. Could it be that you have multiple versions of pysam installed? Could you try to upgrade the pysam version in your virtual environment? I see that you have multiple outdated packages there, it might be better to upgrade all of them (see http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip).
