### ISSUE TITLE
Error  Traceback (most recent call last): line 133, in <module>     import eddlib.experiment

### ISSUE THREAD

**Issue by hfx541** [CollasLab/edd#20]
I would greatly appreciate any help on this error. I had re-installed statsmodel 0.9.0 thinking this might be the issue, but didnt seem to change anything. Any help would be greatly appreciated.

edd -g 5 --write-bin-score hg19.chromsizes hg19_unalignable_regions.bed BL2_CT_R1_rd.bam BL2_CTR2_rd.bam chipseq

Traceback (most recent call last):
  File "/data/home/hfx541/.local/bin/edd", line 133, in <module>
    import eddlib.experiment
  File "/data/home/hfx541/.local/lib/python2.7/site-packages/eddlib/experiment.py", line 19, in <module>
    import estimate
  File "/data/home/hfx541/.local/lib/python2.7/site-packages/eddlib/estimate.py", line 1, in <module>
    from algorithm.max_segments import GenomeBins, IntervalTest
  File "/data/home/hfx541/.local/lib/python2.7/site-packages/eddlib/algorithm/max_segments.py", line 7, in <module>
    import unalignable_regions
  File "/data/home/hfx541/.local/lib/python2.7/site-packages/eddlib/algorithm/unalignable_regions.py", line 5, in <module>
    import pybedtools
  File "/data/home/hfx541/.local/lib/python2.7/site-packages/pybedtools/__init__.py", line 16, in <module>
    from . import contrib
  File "/data/home/hfx541/.local/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 4, in <module>
    from . import long_range_interaction
  File "/data/home/hfx541/.local/lib/python2.7/site-packages/pybedtools/contrib/long_range_interaction.py", line 357
    print("%d (%.1f%%)\r" % (c, c / float(n) * 100), end="")
                                                        ^

**Comment by sarahhp** [comment]
Aha! I just ran into this issue too.  pybedtools installation seems to be python3 (hence the print statement with brackets) whilst edd runs in python 2, so we need to downgrade pybedtools to an earlier version.  

For me that meant reinstalling pybedtools with conda, making sure it didn't update pysam or statsmodel in the process. 

I hope this helps!

**Comment by rabdill** [comment]
Same issue here. They don't explicitly say it in [their changelog](http://daler.github.io/pybedtools/changes.html), but I believe pybedtools removed Python 2 compatibility starting in version 0.9. `pip install pybedtools==0.8.2` did the trick for me.

**Comment by hfx541** [comment]
Thank you both for helping. I will try it this way

**Comment by hfx541** [comment]
installing pybedtools==0.8.2 has solved the issue.
Many thanks
