### ISSUE TITLE
Problem running edd without a defined gap

### ISSUE THREAD

**Issue by runningvato** [CollasLab/edd#9]
Hello,

Edd runs to completion when I specify a gap penalty score, but hangs up with the following error when I don't specify a gap penalty:

Traceback (most recent call last):
  File "/usr/local/bin/edd", line 146, in <module>
    main(args, config)
  File "/usr/local/bin/edd", line 69, in main
    df = loader.get_df(args.unalignable_regions.name)
  File "/usr/local/lib/python2.7/dist-packages/eddlib/experiment.py", line 201, in get_df
    mc_trials=100, pval_lim=0.05)
  File "/usr/local/lib/python2.7/dist-packages/eddlib/estimate.py", line 89, in instantiate
    util.save_bin_score_file(binscore_df, bedgraph_path)
  File "/usr/local/lib/python2.7/dist-packages/eddlib/util.py", line 10, in save_bin_score_file
    df['chrom start end score'.split()].sort(['chrom', 'start']).to_csv(
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

All dependencies were up-to-date and installed prior to installing Edd. Any ideas on what to do?

Thanks for your time!

**Comment by eivindgl** [comment]
Thank you for notifying me. The issue was a non backwards compatible change in the Pandas library EDD depends on. I have updated EDD and version 1.1.18 works with the most recent pandas version.
run `pip install -U edd` to upgrade

**Comment by runningvato** [comment]
Problem solved! Thanks for the speedy response.
